FROM node:20-alpine

WORKDIR /app

# Copier les fichiers de configuration
COPY package*.json ./
COPY tsconfig*.json ./
COPY nest-cli.json ./

# Nettoyer le cache npm après installation pour réduire la taille de l'image
RUN npm install && npm cache clean --force

# Copier le code source (sera overridé par le volume en dev)
COPY src ./src

EXPOSE 3000

CMD ["npm", "run", "start:dev"]
