FROM node:20-alpine

WORKDIR /app

# Copier les fichiers de configuration
COPY package*.json ./
COPY tsconfig*.json ./
COPY nest-cli.json ./

# Installer les dépendances
RUN npm install

# Copier le code source (sera overridé par le volume en dev)
COPY src ./src

EXPOSE 3000

CMD ["npm", "run", "start:dev"]
